#!/usr/bin/env bash

# This file is part of bash-agent.
# Copyright (C) 2026 Andrea Rossini
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -u
set -o pipefail

# show_help returns an OpenAI function definition, the engine will attach it to
# the chat context.
show_help() {
echo '{
      "type": "function",
      "function": {
        "name": "execute",
        "description": "Runs a command in the bash shell.",
        "parameters": {
          "type": "object",
          "required": ["command"],
          "properties": {
            "command": {"type": "string", "description": "The command or series of commands to run inside bash."}
          }
        }
      }
    }'

 exit 0
}

# Mandatory infomode flag.
infomode=

# Parse options
# Add parameters as required. Colon defines the parameter has a value
while getopts hi opt
do
    case $opt in
    h)  show_help;;
    i)  infomode=1;;
    ?)  exit 2;;
    esac
done

shift $((OPTIND - 1))

# Example parameter extraction, customize as needed
command=$(echo "$@" | jq -r '.command')

# Infomode allows the tool to customize its tool calling log message.
# Mandatory exit 0 for allowing the engine to ask the user for permission.
if [[ "$infomode" == "1" ]]; then
    echo EXECUTE "$command" >&2
    exit 0
fi

#=============================
# Your actual code goes here.
#=============================
bash -c -- "$command"

