#!/usr/bin/env bash

# This file is part of bash-agent.
# Copyright (C) 2026 Andrea Rossini
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -u
set -o pipefail

# show_help returns an OpenAI function definition, the engine will attach it to
# the chat context.
show_help() {
echo '{
      "type": "function",
      "function": {
        "name": "execute",
        "description": "Runs a command in the bash shell.",
        "parameters": {
          "type": "object",
          "required": ["command"],
          "properties": {
            "command": {"type": "string", "description": "The command or series of commands to run inside bash."},
            "cwd": {"type": "string", "description": "The working directory for the requested command, an empty or missing value will cause the command to run in the main current directory."},
            "timeout": {"type": "string", "description": "A timeout, in seconds, for the requested command. If the command does not end in the given time, it will fail."}
          }
        }
      }
    }'

 exit 0
}

# Mandatory infomode flag.
infomode=

# Parse options
while getopts hi opt
do
    case $opt in
    h)  show_help;;
    i)  infomode=1;;
    ?)  exit 2;;
    esac
done

shift $((OPTIND - 1))

# Parameter extraction
command=$(echo "$@" | jq -r '.command')
cwd=$(echo "$@" | jq -r '""+.cwd')
timeout=$(echo "$@" | jq -r '""+.timeout')

# Infomode allows the tool to customize its tool calling log message.
# Mandatory exit 0 for allowing the engine to ask the user for permission.
if [[ "$infomode" == "1" ]]; then
    echo "**EXECUTE**"
    echo ""
    echo "\`\`\`bash"
    echo "$command"
    echo "\`\`\`"
    exit 0
fi

#=============================
# Your actual code goes here.
#=============================

if [[ "$cwd" != "" ]]; then
   cd "$cwd"
fi

if [[ "$timeout" != "" ]]; then
    timeout -k3 "$timeout"s bash -c -- "$command"
else
    bash -c -- "$command"
fi

