#!/usr/bin/env bash

# This file is part of bash-agent.
# Copyright (C) 2026 Andrea Rossini
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -u
set -o pipefail

# show_help returns an OpenAI function definition, the engine will attach it to
# the chat context.
show_help() {
echo '{
      "type": "function",
      "function": {
        "name": "write",
        "description": "Writes the entire content to a file; this tool is the preferred method to create new files.",
        "parameters": {
          "type": "object",
          "required": ["file","content"],
          "properties": {
            "file": {"type": "string", "description": "The path of the file relative to the working directory, or an absolute path. If the file exists, it will be overwritten."},
            "content": {"type": "string", "description": "The entire string content to write in the file, or empty string to create an empty file."}
          }
        }
      }
    }'

 exit 0
}

# Mandatory infomode flag.
infomode=

# Parse options
# It is expected to only have h and i
while getopts hi opt
do
    case $opt in
    h)  show_help;;
    i)  infomode=1;;
    ?)  exit 2;;
    esac
done

shift $((OPTIND - 1))

# Extract parameters
file=$(echo "$@" | jq -r '.file')
content=$(echo "$@" | jq -r '.content')

# Infomode allows the tool to customize its tool calling log message.
# Mandatory exit 0 for allowing the engine to ask the user for permission.
if [[ "$infomode" == "1" ]]; then
    echo "**WRITE** \`$file\`"
    echo ""
    echo "\`\`\`"
    echo "$content" | head -n 10
    echo "..."
    echo "\`\`\`"

    exit 0
fi

#=============================
# Your actual code goes here.
#=============================
echo "$content" > "$file"

echo "Successfully wrote $file" >&2
