#!/usr/bin/env bash

# This file is part of bash-agent.
# Copyright (C) 2026 Andrea Rossini
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# --- Strict Mode Configuration ---
# Exit immediately if a command exits with a non-zero status
set -e
# Treat unset variables as an error
set -u
# Catch errors in pipelines (e.g., cmd1 | cmd2 fails if cmd1 fails)
set -o pipefail
# Disable globbing for safety (optional, but good for file handling)
set -f

# Feature switches
enable_pandoc=

# Detect input source
is_a_tty=

if [ -t 0 ]; then
    is_a_tty=1

    which pandoc > /dev/null 2>&1 && enable_pandoc=1
fi

BA_AGENT_CONTEXT=$(mktemp --suffix=.json)
BA_AGENT_TEMP_CONTEXT=$(mktemp --suffix=.json)
BA_AGENT_TOOL_STDOUT=$(mktemp --suffix=.txt)
BA_AGENT_TOOL_STDERR=$(mktemp --suffix=.txt)

response=
answer=

# --- LOGGING HELPER ---
# Simply redirects all parameters to stderr
log() {
    if [[ $is_a_tty == "1" ]]; then
        echo $@ >&2
    fi
}

# --- Cleanup / Signal Handling ---
# Run this when the script exits (normal or error)
cleanup() {
    rm $BA_AGENT_CONTEXT
    rm $BA_AGENT_TEMP_CONTEXT
    rm $BA_AGENT_TOOL_STDOUT
    rm $BA_AGENT_TOOL_STDERR
}
trap cleanup EXIT

# --- Swap context ---
# Swap the file usage for contex/temp context
swap_context() {
    c=$BA_AGENT_CONTEXT
    BA_AGENT_CONTEXT=$BA_AGENT_TEMP_CONTEXT
    BA_AGENT_TEMP_CONTEXT=$c
}

# --- Markdown cat ---
# Passes stdin through pandoc to pretty print markdown
mdcat() {
    if [[ "$enable_pandoc" == "1" ]]; then
        pandoc -i - -w ansi -o -
    else
        cat
    fi
}

# --- Calls llm, updates the context and prints the answer ---
# Since the piped prompt is processed outside the agent loop, this factors code
# that would otherwise be repeated.
call_llm_updatecontext_and_print() {
    response=$(cat $BA_AGENT_CONTEXT | $BA_PATH/ba-curl)

    answer=$(echo $response | jq '.choices[0].message | {role: .role, content: .content, tool_calls: .tool_calls}')

    jq '.messages += [ $ARGS.positional[0] ]' \
        $BA_AGENT_CONTEXT \
        --jsonargs -- "$answer" > $BA_AGENT_TEMP_CONTEXT
    swap_context

    if [[ $(echo $answer | jq -r '.content | length') != "0" ]]; then
        log ""
        echo $answer | jq -r '.content' | mdcat
    fi
}

# --- Attach file ---
# Attaches a file to the chat context
attach() {
    ls "$1" &&
        jq '.messages += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $ARGS.positional[1] }]' \
        $BA_AGENT_CONTEXT \
        --args -- "$1" "$(cat "$1")" > $BA_AGENT_TEMP_CONTEXT &&
        swap_context
}

# --- Attach instructions ---
# Attaches current project agent instructions file to the chat context.
# If no instructions file is found just succedes silently.
attach_instructions() {
    attach ./AGENT.md || \
    attach ./AGENTS.md || \
    attach ./CLAUDE.md || \
    attach ./.github/copilot-instructions.md || \
    true
}

# --- Ask approval ---
# Asks the user to approve a tool call, optionally providing
# steering feedback.
ask_approval() {
    local -n retval=$1

    read -r -e -p "Approve? Type Y, N or a message> " approval

    if [[ "$approval" == "Y" || "$approval" == "y" ]]; then
        return 0
    elif [[ "$approval" == "N" || "$approval" == "n" ]]; then
        retval="User rejected the tool call."
        return 1
    fi

    retval="User rejected with feedback: ""$approval"
    return 2
}

# --- Main Script Logic ---
# Performs initialization, creates an initial context with:
# * System prompt
# * Available tools
#
# Then the script enters the agent loop.
main() {
    # Attach system prompt to the context
    echo '{}' | jq '.={
        tools: [],
        messages: [{
            role: "system",
            content: $ARGS.positional[0]
        }]
    }' --args -- "$(cat "$BA_PATH"/SYSTEM.md)" > $BA_AGENT_CONTEXT

    # Attach tool definitions to the context.
    for t in $(ls "$BA_TOOLS_PATH"); do
        jq '.tools += [$ARGS.positional[0]]' $BA_AGENT_CONTEXT --jsonargs -- "$("$BA_TOOLS_PATH"/$t -h)" > $BA_AGENT_TEMP_CONTEXT && swap_context || log Ignoring tool: "$t"
    done

    # Attach agent instructions to the context
    attach_instructions > /dev/null 2>&1

    answer="{}"

    # If the prompt is piped in, consume the entire stdin
    # and do a call
    if [[ ! $is_a_tty == "1" ]]; then
        jq '.messages += [{role: "user", content: $ARGS.positional[0] }]' \
            $BA_AGENT_CONTEXT \
            --args -- "$(cat)" > $BA_AGENT_TEMP_CONTEXT
        swap_context
        call_llm_updatecontext_and_print
    fi

    # --- MAIN SHELL LOOP ---
    while true
    do
        tool_calls=$(echo $answer | jq '.tool_calls')
        tool_calls_len=$(echo $tool_calls | jq '. | length')

        if [[ "$tool_calls_len" == "0" && $is_a_tty == "1" ]]; then
            # Read user prompt if there is no tool call
            # and it's running interactively
            log ""
            log "------ $PWD ------"
            read -r -e -p "> " prompt

            jq '.messages += [{role: "user", content: $ARGS.positional[0] }]' \
                $BA_AGENT_CONTEXT \
                --args  -- "$prompt" > $BA_AGENT_TEMP_CONTEXT
            swap_context
        elif [[ "$tool_calls_len" == "0" ]]; then
            # Exit the non interactive execution
            exit 0
        else
            # Call all tools requested by the LLM
            while [[ "$tool_calls_len" != "0" ]]; do
                # Extract data from the first item
                name=$(echo $tool_calls | jq -r '""+.[0].function.name')
                tool_call_id=$(echo $tool_calls | jq -r '""+.[0].id')
                arguments=$(echo $tool_calls | jq -r '""+.[0].function.arguments')

                # Drop the first item
                tool_calls=$(echo $tool_calls | jq '.[1:]')
                tool_calls_len=$(echo $tool_calls | jq '. | length')

                exit_status=

                if [[ $is_a_tty == "1" ]]; then
                    log ""
                    "$BA_TOOLS_PATH"/$name -i "$arguments" | mdcat

                    set +e
                    feedback=
                    ask_approval feedback
                    exit_status=$?
                    set -e

                    if [[ "$exit_status" == "0" ]]; then
                        set +e
                        "$BA_TOOLS_PATH"/$name "$arguments" \
                            > "$BA_AGENT_TOOL_STDOUT" \
                            2> "$BA_AGENT_TOOL_STDERR"

                        exit_status=$?
                        set -e
                    else
                        echo "" > "$BA_AGENT_TOOL_STDOUT"
                        echo "$feedback" > "$BA_AGENT_TOOL_STDERR"
                    fi
                else
                    set +e
                    "$BA_TOOLS_PATH"/$name "$arguments" \
                        > "$BA_AGENT_TOOL_STDOUT" \
                        2> "$BA_AGENT_TOOL_STDERR"

                    exit_status=$?
                    set -e
                fi

                jq \
                    --rawfile so "$BA_AGENT_TOOL_STDOUT" \
                    --rawfile se "$BA_AGENT_TOOL_STDERR" \
                '.messages += [{
                    role: "tool",
                    tool_call_id: $ARGS.positional[0],
                    content: ({
                        output: $so,
                        error: $se,
                        exit_status: $ARGS.positional[1]
                    } | tostring)
                }]' \
                    $BA_AGENT_CONTEXT \
                    --args -- "$tool_call_id" "$exit_status" \
                    > $BA_AGENT_TEMP_CONTEXT

                swap_context
            done
        fi

        # Call the LLM with the new context
        call_llm_updatecontext_and_print
    done
}

# Run main function
main "$@"

