#!/usr/bin/env bash

# This file is part of bash-agent.
# Copyright (C) 2026 Andrea Rossini
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# --- Strict Mode Configuration ---
# Exit immediately if a command exits with a non-zero status
set -e
# Treat unset variables as an error
set -u
# Catch errors in pipelines (e.g., cmd1 | cmd2 fails if cmd1 fails)
set -o pipefail
# Disable globbing for safety (optional, but good for file handling)
set -f

# Feature switches
enable_pandoc=

# Detect input source
is_a_tty=

if [ -t 0 ]; then
    is_a_tty=1

    which pandoc > /dev/null 2>&1 && enable_pandoc=1
fi

# Setup env vars
declare -x BA_AUTO_APPROVE="${BA_AUTO_APPROVE:-N}"
declare -x BA_ATTACHMENT_TTL="${BA_ATTACHMENT_TTL:-5}"

# Setup temp files
BA_AGENT_TEMP_FOLDER="$(mktemp -d --suffix=.bash-agent)"
BA_AGENT_CONTEXT="$BA_AGENT_TEMP_FOLDER"/context-a.json
BA_AGENT_TEMP_CONTEXT="$BA_AGENT_TEMP_FOLDER"/context-b.json
BA_AGENT_TOOL_STDOUT="$BA_AGENT_TEMP_FOLDER"/tool-stdout.txt
BA_AGENT_TOOL_STDERR="$BA_AGENT_TEMP_FOLDER"/tool-stderr.txt
response="$BA_AGENT_TEMP_FOLDER"/response.json
answer="$BA_AGENT_TEMP_FOLDER"/answer.json
tool_calls="$BA_AGENT_TEMP_FOLDER"/tool_calls.json

token_usage=0
BA_LAST_MODEL=
BA_LAST_SPEED=
BA_LAST_PROMPT_SPEED=

declare -a attachments
attachments=()
declare -a attachments_ttl
attachments_ttl=()

# --- LOGGING HELPER ---
# Simply redirects all parameters to stderr
log() {
    if [[ $is_a_tty == "1" ]]; then
        echo $@ >&2
    fi
}

# --- Cleanup / Signal Handling ---
# Run this when the script exits (normal or error)
cleanup() {
    rm -R "$BA_AGENT_TEMP_FOLDER"
}
trap cleanup EXIT

# --- Swap context ---
# Swap the file usage for contex/temp context
swap_context() {
    local c
    c="$BA_AGENT_CONTEXT"
    BA_AGENT_CONTEXT="$BA_AGENT_TEMP_CONTEXT"
    BA_AGENT_TEMP_CONTEXT="$c"
}

# --- Markdown cat ---
# Passes stdin through pandoc to pretty print markdown
mdcat() {
    if [[ "$enable_pandoc" == "1" ]]; then
        pandoc -i - -w ansi -o -
    else
        cat
    fi
}

# --- Attach file ---
# Permanently attaches a file to the chat context
attach() {
    ls "$1" &&
        jq '.messages += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $content }]' \
        "$BA_AGENT_CONTEXT" \
        --rawfile content "$1" \
        --args -- "$1" > "$BA_AGENT_TEMP_CONTEXT" &&
        swap_context
}

# --- Attach instructions ---
# Permanently attaches current project agent instructions file to the chat
# context.
# If no instructions file is found just succedes silently.
attach_instructions() {
    attach ./AGENT.md || \
    attach ./AGENTS.md || \
    attach ./CLAUDE.md || \
    attach ./.github/copilot-instructions.md || \
    true
}

# --- Load attachments ---
# Loads the files specified in the attachments array, and builds a series of
# messages with the file contents.
load_attachments() {
    local messages
    messages='[]'

    for f in "${attachments[@]}"; do
        if [[ -f "$f" ]]; then
            messages=$( \
                echo "$messages" | jq '. += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $content }]' \
                --rawfile content <(grep -n '' "$f") \
                --args -- "$f" \
            )
        fi
    done

    echo "$messages"
}

# --- Add attachment ---
# Adds a file to the list of the attachments
add_attachment() {
    local i file found_index
    file="$1"

    if [[ -f "$file" ]]; then
        found_index=-1

        # Search for the file in the attachments list.
        # If we find it, reset its TTL.
        for i in "${!attachments[@]}"; do
            if [[ "${attachments[$i]}" == "$file" ]]; then
                found_index=$i
                break
            fi
        done

        if (( found_index >= 0 )); then
            attachments_ttl[$found_index]=$BA_ATTACHMENT_TTL
        else
            attachments+=("$file")
            attachments_ttl+=($BA_ATTACHMENT_TTL)
        fi
    else
        echo "read: file not found $file" >&2
        return 1
    fi

    return 0
}

# --- Ask approval ---
# Asks the user to approve a tool call, optionally providing
# steering feedback.
ask_approval() {
    local -n retval="$1"
    local approval

    approval=""

    while [[ -z "$approval" ]]; do
        read -r -e -p "Approve? Type Y, N or a message> " approval
    done

    if [[ "$approval" == "Y" || "$approval" == "y" ]]; then
        return 0
    elif [[ "$approval" == "N" || "$approval" == "n" ]]; then
        retval="User rejected the tool call."
        return 1
    fi

    retval="User rejected with feedback: $approval"
    return 2
}

# --- Trim context ---
trim_context() {
    local i
    # Drop attachments older than 5 turns
    # TODO: Drop messages older than 10 turns
    # TODO: Compact context every 10 messages.
    for ((i=0; i<${#attachments_ttl[@]}; i++)); do
        attachments_ttl[$i]=$((${attachments_ttl[$i]} - 1))

        if [[ ${attachments_ttl[$i]} -eq 0 ]]; then
            unset "attachments[$i]"
            unset "attachments_ttl[$i]"
        fi
    done

    # Compaction
    attachments=("${attachments[@]}")
    attachments_ttl=("${attachments_ttl[@]}")
}

# --- Calls llm, updates the context and prints the answer ---
# Since the piped prompt is processed outside the agent loop, this factors code
# that would otherwise be repeated.
call_llm_updatecontext_and_print() {
    # Before sending, context should be trimmed
    trim_context

    cat "$BA_AGENT_CONTEXT" | \
        jq '.messages += $messages[0]' \
        --slurpfile messages <(load_attachments) | \
        "$BA_PATH"/ba-curl > "$response"

    jq '.choices[0].message | {role: .role, content: .content, reasoning_content: .reasoning_content, tool_calls: .tool_calls}' "$response" > "$answer"

    # Extract model name and generation speed from response
    BA_LAST_MODEL=$(jq -r '.model // empty' "$response")
    BA_LAST_PROMPT_SPEED=$(jq -r '.timings.prompt_per_second // empty' "$response")
    BA_LAST_SPEED=$(jq -r '.timings.predicted_per_second // empty' "$response")
    token_usage=$(jq -r '.usage.prompt_tokens // empty' "$response")

    log "Token usage: $token_usage"

    # Update the context
    jq '.messages += [ $answer[0] ]' \
        $BA_AGENT_CONTEXT \
        --slurpfile answer "$answer" > "$BA_AGENT_TEMP_CONTEXT"
    swap_context

    if [[ $(jq -r '.content | length' "$answer") != "0" ]]; then
        log ""
        jq -r '.content' "$answer" | mdcat
    fi
}

# --- Call tool ---
# Calls a tool, forcing a builtin implementation for the builtins
# (read and edit). Since this function is likely called with +e, we test every
# interesting program call.
call_tool() {
    local tool path file
    tool="$1"

    if [[ "$tool" == "read" ]]; then
        # Read is builtin. Instead of reading the current state, the file is
        # added to the list of live attachments.
        path=$(echo "$2" | jq -r '.file')

        if ! add_attachment "$path" ; then
            return 1
        fi

        echo "File $path was successfully attached."
        return 0
    elif [[ "$tool" == "edit" ]]; then
        # Edit requires engine validation, we can't allow the LLM to edit a
        # file it doesn't know line numbers of.
        file=$(echo "$2" | jq -r '.file')

        if [[ ! " ${attachments[*]} " =~ [[:space:]]${file}[[:space:]] ]]; then
            echo "File must be read before edit: $file" >&2
            return 1
        fi

        # The tool implementation is left simple, we enrich it here:
        # * Add attachment will reset the TTL of the file we are touching.
        # * An additional message to remind the LLM it doesn't need read.
        add_attachment "$file"

        if ! "$BA_TOOLS_PATH"/"$tool" "$2" ; then
            return 1
        fi

        echo "Remind the attachment is already the updated version."
        return 0
    fi

    "$BA_TOOLS_PATH"/"$tool" "$2"
}

# --- Main Script Logic ---
# Performs initialization, creates an initial context with:
# * System prompt
# * Available tools
#
# Then the script enters the agent loop.
main() {
    # Attach system prompt to the context
    echo '{}' | jq '.={
        tools: [],
        reasoning_format: "auto",
        messages: [{
            role: "system",
            content: $system
        }]
    }' --rawfile system "$BA_PATH"/SYSTEM.md > "$BA_AGENT_CONTEXT"

    # Attach tool definitions to the context.
    local t
    for t in $(ls "$BA_TOOLS_PATH"); do
        jq '.tools += [$toolhelp[0]]' "$BA_AGENT_CONTEXT" --slurpfile toolhelp <("$BA_TOOLS_PATH/$t" -h) > "$BA_AGENT_TEMP_CONTEXT" && swap_context || log Ignoring tool: "$t"
    done

    # Attach agent instructions to the context
    attach_instructions > /dev/null 2>&1

    echo "{}" > "$answer"

    # If the prompt is piped in, consume the entire stdin
    # and do a call
    if [[ ! $is_a_tty == "1" ]]; then
        jq '.messages += [{role: "user", content: $input }]' \
            "$BA_AGENT_CONTEXT" \
            --rawfile input /dev/stdin > "$BA_AGENT_TEMP_CONTEXT"
        swap_context
        call_llm_updatecontext_and_print
    fi

    # --- MAIN SHELL LOOP ---
    while true
    do
        jq '.tool_calls' "$answer" > "$tool_calls"
        tool_calls_len=$(jq '. | length' "$tool_calls")

        if [[ "$tool_calls_len" == "0" && $is_a_tty == "1" ]]; then
            # Read user prompt if there is no tool call
            # and it's running interactively
            log ""
            if [[ -n "$BA_LAST_MODEL" ]]; then
                log "$(printf -- "------ %s - Prompt: %.2f t/s - Generation: %.2f t/s" "$BA_LAST_MODEL" "$BA_LAST_PROMPT_SPEED" "$BA_LAST_SPEED")"
            fi
            log "------ $PWD ------"
            prompt=""

            while [[ -z "$prompt" ]]; do
                read -r -e -p "> " prompt
            done

            jq '.messages += [{role: "user", content: $ARGS.positional[0] }]' \
                "$BA_AGENT_CONTEXT" \
                --args  -- "$prompt" > "$BA_AGENT_TEMP_CONTEXT"
            swap_context
        elif [[ "$tool_calls_len" == "0" ]]; then
            # Exit the non interactive execution
            exit 0
        else
            # Call all tools requested by the LLM
            local i name tool_call_id arguments feedback
            for ((i=0; i<tool_calls_len; i++)); do
                # Extract data from the first item
                name=$(jq -r '""+.['$i'].function.name' "$tool_calls")
                tool_call_id=$(jq -r '""+.['$i'].id' "$tool_calls")
                arguments=$(jq -r '""+.['$i'].function.arguments' "$tool_calls")

                exit_status=

                if [[ $is_a_tty == "1" ]]; then
                    log ""
                    "$BA_TOOLS_PATH"/$name -i "$arguments" | mdcat
                fi

                if [[ $is_a_tty == "1" ]]; then
                    if [[ $BA_AUTO_APPROVE == "Y" ]]; then
                        exit_status=0
                    else
                        set +e
                        feedback=
                        ask_approval feedback
                        exit_status="$?"
                        set -e
                    fi

                    if [[ "$exit_status" == "0" ]]; then
                        set +e
                        call_tool "$name" "$arguments" \
                            > "$BA_AGENT_TOOL_STDOUT" \
                            2> "$BA_AGENT_TOOL_STDERR"
                        exit_status=$?

                        if [[ "$exit_status" == "0" ]]; then
                            log "OK"
                        else
                            log "Failed"
                        fi

                        set -e
                    else
                        echo "" > "$BA_AGENT_TOOL_STDOUT"
                        echo "$feedback" > "$BA_AGENT_TOOL_STDERR"
                    fi
                else
                    set +e
                    call_tool "$name" "$arguments" \
                        > "$BA_AGENT_TOOL_STDOUT" \
                        2> "$BA_AGENT_TOOL_STDERR"

                    exit_status="$?"
                    set -e
                fi

                jq \
                    --rawfile so "$BA_AGENT_TOOL_STDOUT" \
                    --rawfile se "$BA_AGENT_TOOL_STDERR" \
                '.messages += [{
                    role: "tool",
                    tool_call_id: $ARGS.positional[0],
                    content: ({
                        output: $so,
                        error: $se,
                        exit_status: $ARGS.positional[1]
                    } | tostring)
                }]' \
                    "$BA_AGENT_CONTEXT" \
                    --args -- "$tool_call_id" "$exit_status" \
                    > "$BA_AGENT_TEMP_CONTEXT"

                swap_context
            done
        fi

        # Call the LLM with the new context
        call_llm_updatecontext_and_print
    done
}

# Run main function
main "$@"
