#!/usr/bin/env bash

# show_help returns an OpenAI function definition, the engine will attach it to
# the chat context.
show_help() {
echo '{
      "type": "function",
      "function": {
        "name": "read",
        "description": "Reads the entire content of a file.",
        "parameters": {
          "type": "object",
          "required": ["file"],
          "properties": {
            "file": {"type": "string", "description": "The path of the file relative to the working directory, or an absolute path."}
          }
        }
      }
    }'

 exit 0
}

# Mandatory infomode flag.
infomode=

# Parse options
# It is expected to only have h and i
while getopts hi opt
do
    case $opt in
    h)  show_help;;
    i)  infomode=1;;
    ?)  exit 2;;
    esac
done

shift $((OPTIND - 1))

# Extract parameters
path=$(echo "$@" | jq -r '.file')

# Infomode allows the tool to customize its tool calling log message.
# Mandatory exit 0 for allowing the engine to ask the user for permission.
if [[ "$infomode" == "1" ]]; then
    echo READ $path >&2
    exit 0
fi

# read is implemented as a simple cat
# we launched a space rocket to get from the living room to the kitchen
cat "$path"

