#!/usr/bin/env bash

# show_help returns an OpenAI function definition, the engine will attach it to
# the chat context.
show_help() {
echo '{
      "type": "function",
      "function": {
        "name": "write",
        "description": "Writes the entire content to a file; this tool is the preferred method to create new files.",
        "parameters": {
          "type": "object",
          "required": ["file"],
          "properties": {
            "file": {"type": "string", "description": "The path of the file relative to the working directory, or an absolute path. If the file exists, it will be overwritten."},
            "content": {"type": "string", "description": "The entire string content to write in the file, or empty to create an empty file."}
          }
        }
      }
    }'

 exit 0
}

# Mandatory infomode flag.
infomode=

# Parse options
# It is expected to only have h and i
while getopts hi opt
do
    case $opt in
    h)  show_help;;
    i)  infomode=1;;
    ?)  exit 2;;
    esac
done

shift $((OPTIND - 1))

# Extract parameters
path=$(echo "$@" | jq -r '.file')
content=$(echo "$@" | jq -r '.content')

# Infomode allows the tool to customize its tool calling log message.
# Mandatory exit 0 for allowing the engine to ask the user for permission.
if [[ "$infomode" == "1" ]]; then
    echo WRITE $path >&2
    echo "$content" | head -n 10 >&2
    echo "..." >&2

    exit 0
fi

#=============================
# Your actual code goes here.
#=============================
echo "$content" > "$path"

echo "Successfully wrote $file" >&2
